version: '3'

networks:
  workshop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.23.0/24

services:
  spark:
    image: docker.io/bitnami/spark:3.1.1
    networks:
      workshop:
        ipv4_address: 172.23.23.23
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
